services:
  next-app:
    container_name: next-app
    build:
      context: ./frontend
      dockerfile: Dockerfile

    # Set environment variables directly in the compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set environment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./next-app/src:/app/src
      - ./next-app/public:/app/public
    restart: always
    ports:
      - 3000:3000

  strapi:
    build: 
      context: ./strapi
      dockerfile: Dockerfile
    image: strapi/strapi
    container_name: strapi
    environment:
      DATABASE_CLIENT: postgres # type of database in use
      DATABASE_NAME: ${POSTGRES_DB} # corresponds to POSTGRES_DB (database name)
      DATABASE_HOST: postgres # service name DATABASE_PORT: 5432 #default port 
      DATABASE_USERNAME: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_SSL: ${STRAPI_SSL}
    ports:
      # Host port - access from outside 
      # Container port - access between service-to-service
      - "1337:1337" # HOST_PORT:CONTAINER_PORT
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    environment: 
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes: 
      - pddata:/var/lib/postgresql/data

volumes:
  pddata:
